/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugaspraktikum;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author cakkr
 */
public class sewa extends javax.swing.JFrame {

        

           
    /**
     * Creates new form baru
     */
    
    public sewa() {
     initComponents();
     
 //Mengambil model  dari tabel dan menyimpannya dalam objek DefaultTableModel Model
 DefaultTableModel Model = (DefaultTableModel) tampil.getModel();
 //Mendapatkan jumlah baris yang ada dalam model  saat ini
 int rowCount = Model.getRowCount();
 while (rowCount > 0){
 //Menghapus baris terakhir dari model 
 Model.removeRow(rowCount - 1);
 //Memperbarui nilai rowCount setelah penghapusan baris terakhir
 rowCount = Model.getRowCount();
 }
       
    }
public Connection conn;



public void koneksi() throws SQLException {
        try {
            conn = null;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/OOP_2218084?user=root&password=");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(sewa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException e) {
            Logger.getLogger(sewa.class.getName()).log(Level.SEVERE, null, e);
        } catch (Exception es) {
            Logger.getLogger(sewa.class.getName()).log(Level.SEVERE, null, es);
        }
    }

public void tampil() {
        DefaultTableModel tabelhead = new DefaultTableModel();
        tabelhead.addColumn("nama");
        tabelhead.addColumn("nomor");
        tabelhead.addColumn("durasi");
        tabelhead.addColumn("mode");
        tabelhead.addColumn("jeniskamar");
        tabelhead.addColumn("harga kamar");
        tabelhead.addColumn("admin");
        tabelhead.addColumn("total");
        try {
            koneksi();
            String sql = "SELECT * FROM tb_sewa";
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while (res.next()) {
                tabelhead.addRow(new Object[]{res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7),res.getString(8), });
            }
            tampil.setModel(tabelhead);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "BELUM TERKONEKSI");
        }
    }

 public void insert() {
        String user  = txtuser.getText();
        String nomor = txtnomor.getText();
        String waktu = txtwaktu.getText();
        isi bo = new isi();
        bo.setuser(txtuser.getText() );
      
        bo.waktu = Integer.parseInt(txtwaktu.getText());

        if(radiosil.isSelected()){
            bo.datakamar(radiosil.getText());
            bo.harga = bo.waktu*50000;
        }
        else if(radiogold.isSelected()){
            bo.datakamar(radiogold.getText());
            bo.harga = bo.waktu*100000;
        }
        else{
            bo.datakamar(radiodia.getText());
            bo.harga = bo.waktu*150000;
        }

        if(radioinc.isSelected()){
            bo.datamode(radioinc.getText());
            bo.harga = bo.harga+50000;
        }else{
            bo.datamode(radionor.getText());
        }
       
        
       
        try {
             bo.setnomor=Integer.parseInt(txtnomor.getText()); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "INPUTAN NOMOR TELEPON BERUPA ANGKA!!!");

        } finally {
            JOptionPane.showMessageDialog(null, "Data Sukses Ditambahkan");
        }
 }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        btnbo = new javax.swing.JButton();
        txtnomor = new javax.swing.JTextField();
        btnclo = new javax.swing.JButton();
        radioinc = new javax.swing.JRadioButton();
        txtwaktu = new javax.swing.JTextField();
        radionor = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        radiosil = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        radiogold = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        radiodia = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tampil = new javax.swing.JTable();
        cmbuser = new javax.swing.JComboBox<>();
        cmbnomor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("jam");

        jLabel5.setText("Mode");

        jLabel6.setText("Jenis Kamar");

        btnbo.setText("Boking");
        btnbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnboActionPerformed(evt);
            }
        });

        txtnomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomorActionPerformed(evt);
            }
        });

        btnclo.setText("Hapus");
        btnclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloActionPerformed(evt);
            }
        });

        radioinc.setText("Incognito");
        radioinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioincActionPerformed(evt);
            }
        });

        txtwaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwaktuActionPerformed(evt);
            }
        });

        radionor.setText("Normal");
        radionor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radionorActionPerformed(evt);
            }
        });

        jLabel1.setText("Persewaan Kamar Apartemen");

        radiosil.setText("Silver");
        radiosil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiosilActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        radiogold.setText("Gold");

        jLabel3.setText("Nomor Telepon");

        radiodia.setText("Diamond");

        jLabel4.setText("Durasi ");

        tampil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Nomor Telepon", "Durasi", "Mode", "Jenis Kamar", "harga kamar", "admin", "total "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tampil);

        cmbuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbuserActionPerformed(evt);
            }
        });

        cmbnomor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(469, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnbo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnclo)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(txtnomor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radionor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radiosil, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radiogold, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioinc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radiodia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtwaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbnomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(cmbuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbnomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtwaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioinc)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radionor)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(radiosil))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radiogold)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radiodia)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnbo)
                            .addComponent(btnclo))
                        .addGap(18, 18, 18)
                        .addComponent(txtnomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnboActionPerformed
        // TODO add your handling code here:
       DefaultTableModel Model = (DefaultTableModel) tampil.getModel();
        // Inisialisasi sebuah ArrayList beruser 'list'
        List list = new ArrayList<>();



        isi bo = new isi();
        bo.setuser(txtuser.getText() );
      
        bo.waktu = Integer.parseInt(txtwaktu.getText());

        if(radiosil.isSelected()){
            bo.datakamar(radiosil.getText());
            bo.harga = bo.waktu*50000;
        }
        else if(radiogold.isSelected()){
            bo.datakamar(radiogold.getText());
            bo.harga = bo.waktu*100000;
        }
        else{
            bo.datakamar(radiodia.getText());
            bo.harga = bo.waktu*150000;
        }

        if(radioinc.isSelected()){
            bo.datamode(radioinc.getText());
            bo.harga = bo.harga+50000;
        }else{
            bo.datamode(radionor.getText());
        }
       
        
        list.add(bo.mencetakuser());
        try {
             bo.setnomor=Integer.parseInt(txtnomor.getText()); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "INPUTAN NOMOR TELEPON BERUPA ANGKA!!!");

        } finally {
            JOptionPane.showMessageDialog(null, "Data Sukses Ditambahkan");
        }
        list.add(bo.mencetaknomor());
        list.add(bo.waktu);
        list.add(bo.mencetakmode());
        list.add(bo.mencetakkamar());
        list.add(bo.harga);
        list.add(bo.admin());
        list.add(bo.hittotalkeseluruhan());
        Model.addRow(list.toArray());

    }//GEN-LAST:event_btnboActionPerformed

    private void txtnomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomorActionPerformed

    private void btncloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Model = (DefaultTableModel) tampil.getModel();
        int rowCount = Model.getRowCount();
        while (rowCount > 0) {
            Model.removeRow(rowCount - 1);
            rowCount = Model.getRowCount(); // Update
        }            

    }//GEN-LAST:event_btncloActionPerformed

    private void radioincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioincActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioincActionPerformed

    private void txtwaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwaktuActionPerformed

    private void radionorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radionorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radionorActionPerformed

    private void radiosilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiosilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiosilActionPerformed

    private void cmbuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbo;
    private javax.swing.JButton btnclo;
    private javax.swing.JComboBox<String> cmbnomor;
    private javax.swing.JComboBox<String> cmbuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radiodia;
    private javax.swing.JRadioButton radiogold;
    private javax.swing.JRadioButton radioinc;
    private javax.swing.JRadioButton radionor;
    private javax.swing.JRadioButton radiosil;
    private javax.swing.JTable tampil;
    private javax.swing.JTextField txtnomor;
    private javax.swing.JTextField txtuser;
    private javax.swing.JTextField txtwaktu;
    // End of variables declaration//GEN-END:variables

    private static class rowCount {

        public rowCount() {
        }
    }
}
